spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.199.111.123:3306/ysh?userSSL=false&serverTimezone=GMT%2B8
    username: root
    password: toor
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.theo.entity

redis:

server:
  port: 2020
